import type { TripSnapshot } from "./types";

/** Small, honest local preview used only when the API is unavailable. Production data is seeded by the API. */
export const localPreview: TripSnapshot = {
  version: 0,
  trip: {
    id: "japan-2026",
    name: "Japan 2026",
    startDate: "2026-09-30",
    endDate: "2026-10-25",
    arrival: { airport: "HND", date: "2026-10-02", time: "00:05" },
    departure: { airport: "HND", date: "2026-10-25", time: "01:25" },
  },
  places: [
    {
      id: "p-ginza-itoya",
      name: "Ginza Itoya",
      city: "Tokyo",
      area: "Ginza",
      category: "Culture, Shopping",
      durationText: "45–120 min",
      durationMinutes: 90,
      description:
        "A long-established Ginza stationery flagship with pens, paper, planners and Japanese design goods.",
      notes: "Rainy-day option; exact 2026 hours need checking.",
      googleMapsUrl:
        "https://www.google.com/maps/search/?api=1&query=Ginza+Itoya+Tokyo",
      instagramUrl: "https://www.instagram.com/reel/DaB5EyCPXIU/",
      needsResearch: true,
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-melon-pan",
      name: "Melon Pan 802 Hachioji",
      city: "Tokyo",
      area: "Hachioji",
      category: "Food",
      durationText: "15–30 min",
      durationMinutes: 25,
      description: "Specialist melon pan shop shown in a saved reel.",
      notes: "Only sensible when already in western Tokyo.",
      needsResearch: true,
      priority: "nice",
      status: "Researching",
    },
    {
      id: "p-mikawaya",
      name: "Mikawaya · giant miso katsu",
      city: "Nagoya",
      area: "Mizuho Ward",
      category: "Food",
      durationText: "60–90 min",
      durationMinutes: 75,
      description:
        "Long-established restaurant known for an unusually large miso-katsu set.",
      openingHours: "10:50–14:30 and 17:00–22:30; closed Sunday (verify)",
      reservation: "Unknown",
      needsResearch: true,
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-yokohama-mapo",
      name: "Mapo tofu restaurant · 139 Yamashitacho",
      city: "Yokohama",
      area: "Yokohama Chinatown",
      category: "Food",
      durationText: "45–75 min",
      durationMinutes: 60,
      description: "Silky mapo tofu shown in a saved reel.",
      notes: "Exact business still needs confirmation.",
      needsResearch: true,
      priority: "nice",
      status: "Researching",
    },
    {
      id: "p-asakusa-cafe",
      name: "Fruits Parlor Asakusa Yorozu Cafe 444",
      city: "Tokyo",
      area: "Asakusa",
      category: "Food",
      durationText: "45–90 min plus queue",
      durationMinutes: 75,
      description:
        "Fruit-parlour desserts and visually distinctive café dishes.",
      reservation: "Unknown",
      needsResearch: true,
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-terumae",
      name: "Terumae Ikebukuro Nishiguchi",
      city: "Tokyo",
      area: "Ikebukuro",
      category: "Activity, Food",
      durationText: "90–150 min",
      durationMinutes: 120,
      description:
        "Bathhouse-themed izakaya with self-service faucet drinks and sento décor.",
      reservation: "Recommended",
      needsResearch: true,
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-musashi",
      name: "Menya Musashi · Tokyo locations",
      city: "Tokyo",
      area: "Multiple locations",
      category: "Food",
      durationText: "30–60 min plus queue",
      durationMinutes: 50,
      description: "Tsukemen recommendation with flexible Tokyo branches.",
      notes: "Choose a convenient branch later.",
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-tengu",
      name: "Chikuma Tengu Statue",
      city: "Nagano",
      area: "Chikuma",
      category: "Culture, Sightseeing",
      durationText: "10–20 min",
      durationMinutes: 15,
      description: "A giant tengu statue and novel photo stop.",
      notes: "Only if passing through Chikuma.",
      priority: "nice",
      status: "Saved",
    },
    {
      id: "p-dagashi",
      name: "Dagashi Bar Ebisu",
      city: "Tokyo",
      area: "Ebisu",
      category: "Activity, Culture, Food",
      durationText: "60–120 min",
      durationMinutes: 90,
      description: "Retro Japanese candy-bar experience.",
      reservation: "Recommended",
      needsResearch: true,
      priority: "nice",
      status: "Researching",
    },
    {
      id: "p-katsuoji",
      name: "Katsuo-ji",
      city: "Osaka",
      area: "Minoh",
      category: "Culture, Nature, Sightseeing",
      durationText: "90–150 min plus transport",
      durationMinutes: 120,
      description: "Daruma-filled temple sanctuary in the Minoh area.",
      notes: "A meaningful half-day excursion from Osaka.",
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-kubota",
      name: "Ginjo Ramen Kubota",
      city: "Kyoto",
      area: "Shimogyo Ward",
      category: "Food",
      durationText: "30–60 min plus queue",
      durationMinutes: 50,
      description: "Highly praised tsukemen near Kyoto Station / Gojo.",
      priority: "nice",
      status: "Candidate",
    },
    {
      id: "p-ghibli",
      name: "Ghibli Park",
      city: "Nagoya",
      area: "Aichi",
      category: "Culture, Activity",
      durationText: "4–6 hours",
      durationMinutes: 300,
      description: "Confirmed itinerary anchor.",
      priority: "required",
      status: "Planned",
      selected: true,
    },
  ],
  stays: [
    {
      id: "s-tokyo-arrival",
      city: "Tokyo",
      name: "Arrival night · booking coverage",
      checkIn: "2026-10-01",
      checkOut: "2026-10-03",
      status: "planned",
      bookingId: "b-arrival-hotel",
    },
  ],
  travelLegs: [
    {
      id: "l-tokyo-nagoya",
      from: "Tokyo",
      to: "Nagoya",
      date: "2026-10-08",
      durationMinutes: 110,
      mode: "Shinkansen",
      estimated: true,
    },
  ],
  activities: [
    {
      id: "a-ghibli",
      placeId: "p-ghibli",
      date: "2026-10-12",
      durationMinutes: 300,
      status: "planned",
    },
  ],
  bookings: [
    {
      id: "b-arrival-hotel",
      kind: "hotel",
      title: "Tokyo arrival hotel",
      status: "planned",
      start: "2026-10-01",
      end: "2026-10-03",
      notes: "Check coverage against the late arrival.",
    },
  ],
  tasks: [
    {
      id: "t-passport",
      title: "Check passport expiry",
      dueDate: "2026-09-15",
      completed: false,
      scope: "trip",
    },
    {
      id: "t-ghibli",
      title: "Confirm Ghibli Park entry details",
      dueDate: "2026-09-20",
      completed: false,
      scope: "booking",
    },
  ],
  packingItems: [
    {
      id: "pack-passport",
      name: "Passport",
      category: "Documents",
      quantity: 1,
      packed: false,
      bag: "Personal item",
    },
    {
      id: "pack-adapter",
      name: "Travel adapter",
      category: "Electronics",
      quantity: 1,
      packed: false,
      bag: "Main bag",
    },
    {
      id: "pack-shoes",
      name: "Comfortable walking shoes",
      category: "Clothing",
      quantity: 1,
      packed: true,
      bag: "Main bag",
    },
  ],
};
